In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Ejercicio:

Se desea encontrar el numero de pacientes promedio en el consultorio de un doctor, para ello se realizaron observaciones cada 5 minutos y  se realizaron en la tabla:

| Estado Actual \ Estado Futuro | 0   | 1   | 2   | 3   | 4   |
|-------------------------------|-----|-----|-----|-----|-----|
| 0                             | 3 | 5 | 2 | 0 | 0 |
| 1                             | 8 | 7 | 0 | 1 | 4 |
| 2                             | 5 | 5 | 5 | 5 | 5 |
| 3                             | 5 | 0 | 10 | 0 | 0 |
| 4                             | 1 | 0 | 0 | 0 | 1 |


In [12]:
import numpy as np

data = np.array([
    [3, 5, 2, 0, 0],
    [8, 7, 0, 1, 4],
    [5, 5, 5, 5, 5],
    [5, 0, 10, 0, 0],
    [1, 0, 0, 0, 1]
])

probabilidades_transicion = data / data.sum(axis=1, keepdims=True)
probabilidades_transicion

array([[0.3       , 0.5       , 0.2       , 0.        , 0.        ],
       [0.4       , 0.35      , 0.        , 0.05      , 0.2       ],
       [0.2       , 0.2       , 0.2       , 0.2       , 0.2       ],
       [0.33333333, 0.        , 0.66666667, 0.        , 0.        ],
       [0.5       , 0.        , 0.        , 0.        , 0.5       ]])

In [16]:
valores_propios_u, vectores_propios_u = np.linalg.eig(probabilidades_transicion )

In [19]:
valores_propios_u

array([ 1.        +0.j        , -0.15400864+0.09566897j,
       -0.15400864-0.09566897j,  0.37108642+0.j        ,
        0.28693086+0.j        ])

In [23]:
np.round(vectores_propios_u,2)

array([[-0.45+0.j  ,  0.35+0.25j,  0.35-0.25j, -0.11+0.j  , -0.34+0.j  ],
       [-0.45+0.j  , -0.23-0.15j, -0.23+0.15j,  0.14+0.j  ,  0.03+0.j  ],
       [-0.45+0.j  , -0.34-0.02j, -0.34+0.02j, -0.38+0.j  , -0.05+0.j  ],
       [-0.45+0.j  ,  0.72+0.j  ,  0.72-0.j  , -0.79+0.j  , -0.5 +0.j  ],
       [-0.45+0.j  , -0.23-0.22j, -0.23+0.22j,  0.44+0.j  ,  0.79+0.j  ]])

In [20]:
# Identificar el índice del valor propio 1
indice_valor_propio_1 = np.argmin(np.abs(valores_propios_u - 1))

# Extraer el vector propio correspondiente y tomar solo la parte real
vector_propio_real = np.real(vectores_propios_u[:, indice_valor_propio_1])

# Normalizar el vector para que la suma de sus componentes sea 1
vector_estacionario = vector_propio_real / np.sum(vector_propio_real)

vector_estacionario


array([0.2, 0.2, 0.2, 0.2, 0.2])

In [ ]:
# Recuerda que se usa para el valor propio 1 por que
# PA = lambda * P   # Aqui usamos valores propios y vectores propios
# PA = P  -> # Aqui se usa sistema de ecuaciones

# SVD

In [4]:
# Cálculo de la descomposición en valores singulares (SVD)
U, s, Vt = np.linalg.svd(probabilidades_transicion, full_matrices=True)

# Creación de la matriz Sigma a partir de los valores singulares
Sigma = np.zeros(probabilidades_transicion.shape)
np.fill_diagonal(Sigma, s)

# Redondear las matrices para mejor legibilidad
U_rounded = np.round(U, 3)
Sigma_rounded = np.round(Sigma, 3)
Vt_rounded = np.round(Vt, 3)

#U_rounded, Sigma_rounded, Vt_rounded